#配置服务名称及端口
spring:
  application:
    name:  config-server
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/xuxl/xuxl-springcloud-configs.git
          search-paths:  /**  #配置文件所在的目录
      label: master #配置文件所在的分支
      username:  xuxl #git仓库的用户名
      password:  xuxl0406 #git仓库的密码
      
server:
  port:  9001
#将服务注册到注册中心
eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:1001/eureka/


      
